let a = `hello`;
    console.log(a);
    document.write(a);
    alert(a);
let b = `owu`;
    console.log(b);
    document.write(b);
    alert(b);
let c = `com`;
    console.log(c);
    document.write(c);
    alert(c);
let d = `ua`;
    console.log(d);
    document.write(d);
    alert(d);
let e = 1;
    console.log(e);
    document.write(e);
    alert(e);
let f = 10;
    console.log(f);
    document.write(f);
    alert(f);
let g = -999;
    console.log(g);
    document.write(g);
    alert(g);
let h = 123;
    console.log(h);
    document.write(h);
    alert(h);
let i = 3.14;
    console.log(i);
    document.write(i);
    alert(i);
let j = 2.7;
    console.log(j);
    document.write(j);
    alert(j);
let k = 16;
    console.log(k);
    document.write(k);
    alert(k);
let l = true;
    console.log(l);
    document.write(l);
    alert(l);
let m = false;
    console.log(m);
    document.write(m);
    alert(m);

    let firstName = `Serhii`;
    let middleName = `Volodymyrovich`;
    let lastName = `Bonchkovskyi`;
    let person = firstName + ` ` + middleName + ` ` + lastName;
    console.log(person);

    let aa = 100;
    let bb = `100`;
    let cc = true;
    console. log(typeof aa);
    console. log(typeof bb);
    console. log(typeof cc);

    let messageFirst = prompt(`What is your first name?`);
    console.log(messageFirst);
    let messageSecond = prompt(`What is your middle name?`);
    console.log(messageSecond);
    let messageThird = +prompt(`How old are you?`)
    console.log(messageThird);
